// Complete geographic data for country/state selectors and map integration

export type Country = {
  code: string;   // ISO 3166-1 alpha-2
  name: string;
  flag: string;
  lat: number;
  lng: number;
};

export type StateRegion = {
  code: string;
  name: string;
  lat?: number;
  lng?: number;
};

export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afeganistão", flag: "🇦🇫", lat: 33.93, lng: 67.71 },
  { code: "ZA", name: "África do Sul", flag: "🇿🇦", lat: -30.56, lng: 22.94 },
  { code: "AL", name: "Albânia", flag: "🇦🇱", lat: 41.15, lng: 20.17 },
  { code: "DE", name: "Alemanha", flag: "🇩🇪", lat: 51.17, lng: 10.45 },
  { code: "AD", name: "Andorra", flag: "🇦🇩", lat: 42.55, lng: 1.60 },
  { code: "AO", name: "Angola", flag: "🇦🇴", lat: -11.20, lng: 17.87 },
  { code: "AG", name: "Antígua e Barbuda", flag: "🇦🇬", lat: 17.06, lng: -61.80 },
  { code: "SA", name: "Arábia Saudita", flag: "🇸🇦", lat: 23.89, lng: 45.08 },
  { code: "DZ", name: "Argélia", flag: "🇩🇿", lat: 28.03, lng: 1.66 },
  { code: "AR", name: "Argentina", flag: "🇦🇷", lat: -38.42, lng: -63.62 },
  { code: "AM", name: "Armênia", flag: "🇦🇲", lat: 40.07, lng: 45.04 },
  { code: "AU", name: "Austrália", flag: "🇦🇺", lat: -25.27, lng: 133.78 },
  { code: "AT", name: "Áustria", flag: "🇦🇹", lat: 47.52, lng: 14.55 },
  { code: "AZ", name: "Azerbaijão", flag: "🇦🇿", lat: 40.14, lng: 47.58 },
  { code: "BS", name: "Bahamas", flag: "🇧🇸", lat: 25.03, lng: -77.40 },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩", lat: 23.68, lng: 90.36 },
  { code: "BB", name: "Barbados", flag: "🇧🇧", lat: 13.19, lng: -59.54 },
  { code: "BH", name: "Bahrein", flag: "🇧🇭", lat: 26.00, lng: 50.55 },
  { code: "BE", name: "Bélgica", flag: "🇧🇪", lat: 50.50, lng: 4.47 },
  { code: "BZ", name: "Belize", flag: "🇧🇿", lat: 17.19, lng: -88.50 },
  { code: "BJ", name: "Benin", flag: "🇧🇯", lat: 9.31, lng: 2.32 },
  { code: "BY", name: "Bielorrússia", flag: "🇧🇾", lat: 53.71, lng: 27.95 },
  { code: "BO", name: "Bolívia", flag: "🇧🇴", lat: -16.29, lng: -63.59 },
  { code: "BA", name: "Bósnia e Herzegovina", flag: "🇧🇦", lat: 43.92, lng: 17.68 },
  { code: "BW", name: "Botsuana", flag: "🇧🇼", lat: -22.33, lng: 24.68 },
  { code: "BR", name: "Brasil", flag: "🇧🇷", lat: -14.24, lng: -51.93 },
  { code: "BN", name: "Brunei", flag: "🇧🇳", lat: 4.54, lng: 114.73 },
  { code: "BG", name: "Bulgária", flag: "🇧🇬", lat: 42.73, lng: 25.49 },
  { code: "BF", name: "Burkina Faso", flag: "🇧🇫", lat: 12.36, lng: -1.53 },
  { code: "BI", name: "Burundi", flag: "🇧🇮", lat: -3.37, lng: 29.92 },
  { code: "BT", name: "Butão", flag: "🇧🇹", lat: 27.51, lng: 90.43 },
  { code: "CV", name: "Cabo Verde", flag: "🇨🇻", lat: 16.54, lng: -23.04 },
  { code: "CM", name: "Camarões", flag: "🇨🇲", lat: 3.85, lng: 11.50 },
  { code: "KH", name: "Camboja", flag: "🇰🇭", lat: 12.57, lng: 104.99 },
  { code: "CA", name: "Canadá", flag: "🇨🇦", lat: 56.13, lng: -106.35 },
  { code: "QA", name: "Catar", flag: "🇶🇦", lat: 25.35, lng: 51.18 },
  { code: "KZ", name: "Cazaquistão", flag: "🇰🇿", lat: 48.02, lng: 66.92 },
  { code: "TD", name: "Chade", flag: "🇹🇩", lat: 15.45, lng: 18.73 },
  { code: "CL", name: "Chile", flag: "🇨🇱", lat: -35.68, lng: -71.54 },
  { code: "CN", name: "China", flag: "🇨🇳", lat: 35.86, lng: 104.20 },
  { code: "CY", name: "Chipre", flag: "🇨🇾", lat: 35.13, lng: 33.43 },
  { code: "CO", name: "Colômbia", flag: "🇨🇴", lat: 4.57, lng: -74.30 },
  { code: "KM", name: "Comores", flag: "🇰🇲", lat: -11.64, lng: 43.33 },
  { code: "CG", name: "Congo", flag: "🇨🇬", lat: -0.23, lng: 15.83 },
  { code: "CD", name: "Congo (RDC)", flag: "🇨🇩", lat: -4.04, lng: 21.76 },
  { code: "KP", name: "Coreia do Norte", flag: "🇰🇵", lat: 40.34, lng: 127.51 },
  { code: "KR", name: "Coreia do Sul", flag: "🇰🇷", lat: 35.91, lng: 127.77 },
  { code: "CI", name: "Costa do Marfim", flag: "🇨🇮", lat: 7.54, lng: -5.55 },
  { code: "CR", name: "Costa Rica", flag: "🇨🇷", lat: 9.75, lng: -83.75 },
  { code: "HR", name: "Croácia", flag: "🇭🇷", lat: 45.10, lng: 15.20 },
  { code: "CU", name: "Cuba", flag: "🇨🇺", lat: 21.52, lng: -77.78 },
  { code: "DK", name: "Dinamarca", flag: "🇩🇰", lat: 56.26, lng: 9.50 },
  { code: "DJ", name: "Djibuti", flag: "🇩🇯", lat: 11.83, lng: 42.59 },
  { code: "DM", name: "Dominica", flag: "🇩🇲", lat: 15.41, lng: -61.37 },
  { code: "EG", name: "Egito", flag: "🇪🇬", lat: 26.82, lng: 30.80 },
  { code: "SV", name: "El Salvador", flag: "🇸🇻", lat: 13.79, lng: -88.90 },
  { code: "AE", name: "Emirados Árabes Unidos", flag: "🇦🇪", lat: 23.42, lng: 53.85 },
  { code: "EC", name: "Equador", flag: "🇪🇨", lat: -1.83, lng: -78.18 },
  { code: "ER", name: "Eritreia", flag: "🇪🇷", lat: 15.18, lng: 39.78 },
  { code: "SK", name: "Eslováquia", flag: "🇸🇰", lat: 48.67, lng: 19.70 },
  { code: "SI", name: "Eslovênia", flag: "🇸🇮", lat: 46.15, lng: 14.99 },
  { code: "ES", name: "Espanha", flag: "🇪🇸", lat: 40.46, lng: -3.75 },
  { code: "SZ", name: "Essuatíni", flag: "🇸🇿", lat: -26.52, lng: 31.47 },
  { code: "ET", name: "Etiópia", flag: "🇪🇹", lat: 9.15, lng: 40.49 },
  { code: "FJ", name: "Fiji", flag: "🇫🇯", lat: -16.58, lng: 179.41 },
  { code: "PH", name: "Filipinas", flag: "🇵🇭", lat: 12.88, lng: 121.77 },
  { code: "FI", name: "Finlândia", flag: "🇫🇮", lat: 61.92, lng: 25.75 },
  { code: "FR", name: "França", flag: "🇫🇷", lat: 46.23, lng: 2.21 },
  { code: "GA", name: "Gabão", flag: "🇬🇦", lat: -0.80, lng: 11.61 },
  { code: "GM", name: "Gâmbia", flag: "🇬🇲", lat: 13.44, lng: -15.31 },
  { code: "GH", name: "Gana", flag: "🇬🇭", lat: 7.95, lng: -1.02 },
  { code: "GE", name: "Geórgia", flag: "🇬🇪", lat: 42.32, lng: 43.36 },
  { code: "GD", name: "Granada", flag: "🇬🇩", lat: 12.12, lng: -61.68 },
  { code: "GR", name: "Grécia", flag: "🇬🇷", lat: 39.07, lng: 21.82 },
  { code: "GT", name: "Guatemala", flag: "🇬🇹", lat: 15.78, lng: -90.23 },
  { code: "GN", name: "Guiné", flag: "🇬🇳", lat: 9.95, lng: -11.61 },
  { code: "GW", name: "Guiné-Bissau", flag: "🇬🇼", lat: 11.80, lng: -15.18 },
  { code: "GQ", name: "Guiné Equatorial", flag: "🇬🇶", lat: 1.65, lng: 10.27 },
  { code: "GY", name: "Guiana", flag: "🇬🇾", lat: 4.86, lng: -58.93 },
  { code: "HT", name: "Haiti", flag: "🇭🇹", lat: 18.97, lng: -72.29 },
  { code: "HN", name: "Honduras", flag: "🇭🇳", lat: 15.20, lng: -86.24 },
  { code: "HU", name: "Hungria", flag: "🇭🇺", lat: 47.16, lng: 19.50 },
  { code: "YE", name: "Iêmen", flag: "🇾🇪", lat: 15.55, lng: 48.52 },
  { code: "IN", name: "Índia", flag: "🇮🇳", lat: 20.59, lng: 78.96 },
  { code: "ID", name: "Indonésia", flag: "🇮🇩", lat: -0.79, lng: 113.92 },
  { code: "IQ", name: "Iraque", flag: "🇮🇶", lat: 33.22, lng: 43.68 },
  { code: "IR", name: "Irã", flag: "🇮🇷", lat: 32.43, lng: 53.69 },
  { code: "IE", name: "Irlanda", flag: "🇮🇪", lat: 53.41, lng: -8.24 },
  { code: "IS", name: "Islândia", flag: "🇮🇸", lat: 64.96, lng: -19.02 },
  { code: "IL", name: "Israel", flag: "🇮🇱", lat: 31.05, lng: 34.85 },
  { code: "IT", name: "Itália", flag: "🇮🇹", lat: 41.87, lng: 12.57 },
  { code: "JM", name: "Jamaica", flag: "🇯🇲", lat: 18.11, lng: -77.30 },
  { code: "JP", name: "Japão", flag: "🇯🇵", lat: 36.20, lng: 138.25 },
  { code: "JO", name: "Jordânia", flag: "🇯🇴", lat: 30.59, lng: 36.24 },
  { code: "KE", name: "Quênia", flag: "🇰🇪", lat: -0.02, lng: 37.91 },
  { code: "KI", name: "Quiribati", flag: "🇰🇮", lat: -3.37, lng: -168.73 },
  { code: "KW", name: "Kuwait", flag: "🇰🇼", lat: 29.31, lng: 47.48 },
  { code: "KG", name: "Quirguistão", flag: "🇰🇬", lat: 41.20, lng: 74.77 },
  { code: "LA", name: "Laos", flag: "🇱🇦", lat: 19.86, lng: 102.50 },
  { code: "LS", name: "Lesoto", flag: "🇱🇸", lat: -29.61, lng: 28.23 },
  { code: "LV", name: "Letônia", flag: "🇱🇻", lat: 56.88, lng: 24.60 },
  { code: "LB", name: "Líbano", flag: "🇱🇧", lat: 33.85, lng: 35.86 },
  { code: "LR", name: "Libéria", flag: "🇱🇷", lat: 6.43, lng: -9.43 },
  { code: "LY", name: "Líbia", flag: "🇱🇾", lat: 26.34, lng: 17.23 },
  { code: "LI", name: "Liechtenstein", flag: "🇱🇮", lat: 47.14, lng: 9.55 },
  { code: "LT", name: "Lituânia", flag: "🇱🇹", lat: 55.17, lng: 23.88 },
  { code: "LU", name: "Luxemburgo", flag: "🇱🇺", lat: 49.82, lng: 6.13 },
  { code: "MK", name: "Macedônia do Norte", flag: "🇲🇰", lat: 41.61, lng: 21.75 },
  { code: "MG", name: "Madagascar", flag: "🇲🇬", lat: -18.77, lng: 46.87 },
  { code: "MY", name: "Malásia", flag: "🇲🇾", lat: 4.21, lng: 108.96 },
  { code: "MW", name: "Malawi", flag: "🇲🇼", lat: -13.25, lng: 34.30 },
  { code: "MV", name: "Maldivas", flag: "🇲🇻", lat: 3.20, lng: 73.22 },
  { code: "ML", name: "Mali", flag: "🇲🇱", lat: 17.57, lng: -3.99 },
  { code: "MT", name: "Malta", flag: "🇲🇹", lat: 35.94, lng: 14.38 },
  { code: "MA", name: "Marrocos", flag: "🇲🇦", lat: 31.79, lng: -7.09 },
  { code: "MH", name: "Ilhas Marshall", flag: "🇲🇭", lat: 7.13, lng: 171.18 },
  { code: "MR", name: "Mauritânia", flag: "🇲🇷", lat: 21.01, lng: -10.94 },
  { code: "MU", name: "Maurício", flag: "🇲🇺", lat: -20.35, lng: 57.55 },
  { code: "MX", name: "México", flag: "🇲🇽", lat: 23.63, lng: -102.55 },
  { code: "FM", name: "Micronésia", flag: "🇫🇲", lat: 7.43, lng: 150.55 },
  { code: "MZ", name: "Moçambique", flag: "🇲🇿", lat: -18.67, lng: 35.53 },
  { code: "MD", name: "Moldávia", flag: "🇲🇩", lat: 47.41, lng: 28.37 },
  { code: "MC", name: "Mônaco", flag: "🇲🇨", lat: 43.75, lng: 7.41 },
  { code: "MN", name: "Mongólia", flag: "🇲🇳", lat: 46.86, lng: 103.85 },
  { code: "ME", name: "Montenegro", flag: "🇲🇪", lat: 42.71, lng: 19.37 },
  { code: "MM", name: "Myanmar", flag: "🇲🇲", lat: 21.92, lng: 95.96 },
  { code: "NA", name: "Namíbia", flag: "🇳🇦", lat: -22.96, lng: 18.49 },
  { code: "NR", name: "Nauru", flag: "🇳🇷", lat: -0.52, lng: 166.93 },
  { code: "NP", name: "Nepal", flag: "🇳🇵", lat: 28.39, lng: 84.12 },
  { code: "NI", name: "Nicarágua", flag: "🇳🇮", lat: 12.87, lng: -85.21 },
  { code: "NE", name: "Níger", flag: "🇳🇪", lat: 17.61, lng: 8.08 },
  { code: "NG", name: "Nigéria", flag: "🇳🇬", lat: 9.08, lng: 8.68 },
  { code: "NO", name: "Noruega", flag: "🇳🇴", lat: 60.47, lng: 8.47 },
  { code: "NZ", name: "Nova Zelândia", flag: "🇳🇿", lat: -40.90, lng: 174.89 },
  { code: "OM", name: "Omã", flag: "🇴🇲", lat: 21.51, lng: 55.92 },
  { code: "PW", name: "Palau", flag: "🇵🇼", lat: 7.52, lng: 134.58 },
  { code: "PA", name: "Panamá", flag: "🇵🇦", lat: 8.54, lng: -80.78 },
  { code: "PG", name: "Papua Nova Guiné", flag: "🇵🇬", lat: -6.31, lng: 143.96 },
  { code: "PK", name: "Paquistão", flag: "🇵🇰", lat: 30.38, lng: 69.35 },
  { code: "PY", name: "Paraguai", flag: "🇵🇾", lat: -23.44, lng: -58.44 },
  { code: "PE", name: "Peru", flag: "🇵🇪", lat: -9.19, lng: -75.02 },
  { code: "PL", name: "Polônia", flag: "🇵🇱", lat: 51.92, lng: 19.15 },
  { code: "PT", name: "Portugal", flag: "🇵🇹", lat: 39.40, lng: -8.22 },
  { code: "KE", name: "Quênia", flag: "🇰🇪", lat: -0.02, lng: 37.91 },
  { code: "GB", name: "Reino Unido", flag: "🇬🇧", lat: 55.38, lng: -3.44 },
  { code: "CF", name: "República Centro-Africana", flag: "🇨🇫", lat: 6.61, lng: 20.94 },
  { code: "DO", name: "República Dominicana", flag: "🇩🇴", lat: 18.74, lng: -70.16 },
  { code: "CZ", name: "República Tcheca", flag: "🇨🇿", lat: 49.82, lng: 15.47 },
  { code: "RO", name: "Romênia", flag: "🇷🇴", lat: 45.94, lng: 24.97 },
  { code: "RW", name: "Ruanda", flag: "🇷🇼", lat: -1.94, lng: 29.87 },
  { code: "RU", name: "Rússia", flag: "🇷🇺", lat: 61.52, lng: 105.32 },
  { code: "WS", name: "Samoa", flag: "🇼🇸", lat: -13.76, lng: -172.10 },
  { code: "SM", name: "San Marino", flag: "🇸🇲", lat: 43.94, lng: 12.46 },
  { code: "SH", name: "Santa Helena", flag: "🇸🇭", lat: -24.14, lng: -10.03 },
  { code: "LC", name: "Santa Lúcia", flag: "🇱🇨", lat: 13.91, lng: -60.98 },
  { code: "VC", name: "São Vicente e Granadinas", flag: "🇻🇨", lat: 12.98, lng: -61.29 },
  { code: "ST", name: "São Tomé e Príncipe", flag: "🇸🇹", lat: 0.19, lng: 6.61 },
  { code: "SN", name: "Senegal", flag: "🇸🇳", lat: 14.50, lng: -14.45 },
  { code: "SL", name: "Serra Leoa", flag: "🇸🇱", lat: 8.46, lng: -11.78 },
  { code: "RS", name: "Sérvia", flag: "🇷🇸", lat: 44.02, lng: 21.01 },
  { code: "SC", name: "Seychelles", flag: "🇸🇨", lat: -4.68, lng: 55.49 },
  { code: "SO", name: "Somália", flag: "🇸🇴", lat: 5.15, lng: 46.20 },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰", lat: 7.87, lng: 80.77 },
  { code: "SD", name: "Sudão", flag: "🇸🇩", lat: 12.86, lng: 30.22 },
  { code: "SS", name: "Sudão do Sul", flag: "🇸🇸", lat: 6.88, lng: 31.31 },
  { code: "SE", name: "Suécia", flag: "🇸🇪", lat: 60.13, lng: 18.64 },
  { code: "CH", name: "Suíça", flag: "🇨🇭", lat: 46.82, lng: 8.23 },
  { code: "SR", name: "Suriname", flag: "🇸🇷", lat: 3.92, lng: -56.03 },
  { code: "TJ", name: "Tadjiquistão", flag: "🇹🇯", lat: 38.86, lng: 71.28 },
  { code: "TH", name: "Tailândia", flag: "🇹🇭", lat: 15.87, lng: 100.99 },
  { code: "TW", name: "Taiwan", flag: "🇹🇼", lat: 23.70, lng: 120.96 },
  { code: "TZ", name: "Tanzânia", flag: "🇹🇿", lat: -6.37, lng: 34.89 },
  { code: "TL", name: "Timor-Leste", flag: "🇹🇱", lat: -8.87, lng: 125.73 },
  { code: "TG", name: "Togo", flag: "🇹🇬", lat: 8.62, lng: 0.82 },
  { code: "TO", name: "Tonga", flag: "🇹🇴", lat: -21.18, lng: -175.20 },
  { code: "TT", name: "Trinidad e Tobago", flag: "🇹🇹", lat: 10.69, lng: -61.22 },
  { code: "TN", name: "Tunísia", flag: "🇹🇳", lat: 33.89, lng: 9.54 },
  { code: "TM", name: "Turcomenistão", flag: "🇹🇲", lat: 38.97, lng: 59.56 },
  { code: "TR", name: "Turquia", flag: "🇹🇷", lat: 38.96, lng: 35.24 },
  { code: "TV", name: "Tuvalu", flag: "🇹🇻", lat: -7.11, lng: 177.65 },
  { code: "UA", name: "Ucrânia", flag: "🇺🇦", lat: 48.38, lng: 31.17 },
  { code: "UG", name: "Uganda", flag: "🇺🇬", lat: 1.37, lng: 32.29 },
  { code: "UY", name: "Uruguai", flag: "🇺🇾", lat: -32.52, lng: -55.77 },
  { code: "UZ", name: "Uzbequistão", flag: "🇺🇿", lat: 41.38, lng: 64.59 },
  { code: "VU", name: "Vanuatu", flag: "🇻🇺", lat: -15.38, lng: 166.96 },
  { code: "VA", name: "Vaticano", flag: "🇻🇦", lat: 41.90, lng: 12.45 },
  { code: "VE", name: "Venezuela", flag: "🇻🇪", lat: 6.42, lng: -66.59 },
  { code: "VN", name: "Vietnã", flag: "🇻🇳", lat: 14.06, lng: 108.28 },
  { code: "ZM", name: "Zâmbia", flag: "🇿🇲", lat: -13.13, lng: 27.85 },
  { code: "ZW", name: "Zimbábue", flag: "🇿🇼", lat: -19.02, lng: 29.15 },
  { code: "US", name: "Estados Unidos", flag: "🇺🇸", lat: 37.09, lng: -95.71 },
];

// States/regions by country code
export const STATES_BY_COUNTRY: Record<string, StateRegion[]> = {
  BR: [
    { code: "AC", name: "Acre", lat: -9.02, lng: -70.81 },
    { code: "AL", name: "Alagoas", lat: -9.57, lng: -36.78 },
    { code: "AP", name: "Amapá", lat: 1.41, lng: -51.77 },
    { code: "AM", name: "Amazonas", lat: -3.47, lng: -65.10 },
    { code: "BA", name: "Bahia", lat: -12.58, lng: -41.70 },
    { code: "CE", name: "Ceará", lat: -5.50, lng: -39.32 },
    { code: "DF", name: "Distrito Federal", lat: -15.83, lng: -47.86 },
    { code: "ES", name: "Espírito Santo", lat: -19.19, lng: -40.34 },
    { code: "GO", name: "Goiás", lat: -15.83, lng: -49.84 },
    { code: "MA", name: "Maranhão", lat: -4.97, lng: -45.27 },
    { code: "MT", name: "Mato Grosso", lat: -12.64, lng: -55.42 },
    { code: "MS", name: "Mato Grosso do Sul", lat: -20.51, lng: -54.54 },
    { code: "MG", name: "Minas Gerais", lat: -18.51, lng: -44.56 },
    { code: "PA", name: "Pará", lat: -3.79, lng: -52.48 },
    { code: "PB", name: "Paraíba", lat: -7.24, lng: -36.78 },
    { code: "PR", name: "Paraná", lat: -25.25, lng: -52.02 },
    { code: "PE", name: "Pernambuco", lat: -8.38, lng: -37.86 },
    { code: "PI", name: "Piauí", lat: -7.72, lng: -42.73 },
    { code: "RJ", name: "Rio de Janeiro", lat: -22.91, lng: -43.17 },
    { code: "RN", name: "Rio Grande do Norte", lat: -5.81, lng: -36.59 },
    { code: "RS", name: "Rio Grande do Sul", lat: -30.03, lng: -51.22 },
    { code: "RO", name: "Rondônia", lat: -11.50, lng: -63.58 },
    { code: "RR", name: "Roraima", lat: 1.99, lng: -61.33 },
    { code: "SC", name: "Santa Catarina", lat: -27.33, lng: -50.22 },
    { code: "SP", name: "São Paulo", lat: -23.55, lng: -46.63 },
    { code: "SE", name: "Sergipe", lat: -10.57, lng: -37.45 },
    { code: "TO", name: "Tocantins", lat: -10.25, lng: -48.25 },
  ],
  US: [
    { code: "AL", name: "Alabama" }, { code: "AK", name: "Alaska" }, { code: "AZ", name: "Arizona" },
    { code: "AR", name: "Arkansas" }, { code: "CA", name: "Califórnia" }, { code: "CO", name: "Colorado" },
    { code: "CT", name: "Connecticut" }, { code: "DE", name: "Delaware" }, { code: "FL", name: "Flórida" },
    { code: "GA", name: "Geórgia" }, { code: "HI", name: "Havaí" }, { code: "ID", name: "Idaho" },
    { code: "IL", name: "Illinois" }, { code: "IN", name: "Indiana" }, { code: "IA", name: "Iowa" },
    { code: "KS", name: "Kansas" }, { code: "KY", name: "Kentucky" }, { code: "LA", name: "Louisiana" },
    { code: "ME", name: "Maine" }, { code: "MD", name: "Maryland" }, { code: "MA", name: "Massachusetts" },
    { code: "MI", name: "Michigan" }, { code: "MN", name: "Minnesota" }, { code: "MS", name: "Mississippi" },
    { code: "MO", name: "Missouri" }, { code: "MT", name: "Montana" }, { code: "NE", name: "Nebraska" },
    { code: "NV", name: "Nevada" }, { code: "NH", name: "New Hampshire" }, { code: "NJ", name: "New Jersey" },
    { code: "NM", name: "Novo México" }, { code: "NY", name: "Nova York" }, { code: "NC", name: "Carolina do Norte" },
    { code: "ND", name: "Dakota do Norte" }, { code: "OH", name: "Ohio" }, { code: "OK", name: "Oklahoma" },
    { code: "OR", name: "Oregon" }, { code: "PA", name: "Pensilvânia" }, { code: "RI", name: "Rhode Island" },
    { code: "SC", name: "Carolina do Sul" }, { code: "SD", name: "Dakota do Sul" }, { code: "TN", name: "Tennessee" },
    { code: "TX", name: "Texas" }, { code: "UT", name: "Utah" }, { code: "VT", name: "Vermont" },
    { code: "VA", name: "Virgínia" }, { code: "WA", name: "Washington" }, { code: "WV", name: "Virgínia Ocidental" },
    { code: "WI", name: "Wisconsin" }, { code: "WY", name: "Wyoming" }, { code: "DC", name: "Distrito de Columbia" },
  ],
  AR: [
    { code: "BA", name: "Buenos Aires" }, { code: "CA", name: "Catamarca" }, { code: "CT", name: "Chaco" },
    { code: "CH", name: "Chubut" }, { code: "CB", name: "Córdoba" }, { code: "CR", name: "Corrientes" },
    { code: "ER", name: "Entre Ríos" }, { code: "FO", name: "Formosa" }, { code: "JY", name: "Jujuy" },
    { code: "LP", name: "La Pampa" }, { code: "LR", name: "La Rioja" }, { code: "MZ", name: "Mendoza" },
    { code: "MN", name: "Misiones" }, { code: "NQ", name: "Neuquén" }, { code: "RN", name: "Río Negro" },
    { code: "SA", name: "Salta" }, { code: "SJ", name: "San Juan" }, { code: "SL", name: "San Luis" },
    { code: "SC", name: "Santa Cruz" }, { code: "SF", name: "Santa Fe" }, { code: "SE", name: "Santiago del Estero" },
    { code: "TF", name: "Tierra del Fuego" }, { code: "TU", name: "Tucumán" },
  ],
  CL: [
    { code: "AI", name: "Aysén" }, { code: "AN", name: "Antofagasta" }, { code: "AP", name: "Arica e Parinacota" },
    { code: "AT", name: "Atacama" }, { code: "BI", name: "Biobío" }, { code: "CO", name: "Coquimbo" },
    { code: "AR", name: "La Araucanía" }, { code: "LI", name: "O'Higgins" }, { code: "LL", name: "Los Lagos" },
    { code: "LR", name: "Los Ríos" }, { code: "MA", name: "Magalhães" }, { code: "ML", name: "Maule" },
    { code: "NB", name: "Ñuble" }, { code: "RM", name: "Região Metropolitana" }, { code: "TA", name: "Tarapacá" },
    { code: "VS", name: "Valparaíso" },
  ],
  CO: [
    { code: "AMA", name: "Amazonas" }, { code: "ANT", name: "Antioquia" }, { code: "ARA", name: "Arauca" },
    { code: "ATL", name: "Atlântico" }, { code: "BOL", name: "Bolívar" }, { code: "BOY", name: "Boyacá" },
    { code: "CAL", name: "Caldas" }, { code: "CAQ", name: "Caquetá" }, { code: "CAS", name: "Casanare" },
    { code: "CAU", name: "Cauca" }, { code: "CES", name: "Cesar" }, { code: "CHO", name: "Chocó" },
    { code: "COR", name: "Córdoba" }, { code: "CUN", name: "Cundinamarca" }, { code: "GUA", name: "Guainía" },
    { code: "GUV", name: "Guaviare" }, { code: "HUI", name: "Huila" }, { code: "LAG", name: "La Guajira" },
    { code: "MAG", name: "Magdalena" }, { code: "MET", name: "Meta" }, { code: "NAR", name: "Nariño" },
    { code: "NSA", name: "Norte de Santander" }, { code: "PUT", name: "Putumayo" }, { code: "QUI", name: "Quindío" },
    { code: "RIS", name: "Risaralda" }, { code: "SAP", name: "San Andrés e Providência" }, { code: "SAN", name: "Santander" },
    { code: "SUC", name: "Sucre" }, { code: "TOL", name: "Tolima" }, { code: "VAC", name: "Valle del Cauca" },
    { code: "VAU", name: "Vaupés" }, { code: "VID", name: "Vichada" },
  ],
  PE: [
    { code: "AMA", name: "Amazonas" }, { code: "ANC", name: "Ancash" }, { code: "APU", name: "Apurímac" },
    { code: "ARE", name: "Arequipa" }, { code: "AYA", name: "Ayacucho" }, { code: "CAJ", name: "Cajamarca" },
    { code: "CAL", name: "Callao" }, { code: "CUS", name: "Cusco" }, { code: "HUC", name: "Huánuco" },
    { code: "HUV", name: "Huancavelica" }, { code: "ICA", name: "Ica" }, { code: "JUN", name: "Junín" },
    { code: "LAL", name: "La Libertad" }, { code: "LAM", name: "Lambayeque" }, { code: "LIM", name: "Lima" },
    { code: "LOR", name: "Loreto" }, { code: "MDD", name: "Madre de Dios" }, { code: "MOQ", name: "Moquegua" },
    { code: "PAS", name: "Pasco" }, { code: "PIU", name: "Piura" }, { code: "PUN", name: "Puno" },
    { code: "SAM", name: "San Martín" }, { code: "TAC", name: "Tacna" }, { code: "TUM", name: "Tumbes" },
    { code: "UCA", name: "Ucayali" },
  ],
  MX: [
    { code: "AGU", name: "Aguascalientes" }, { code: "BCN", name: "Baja California" }, { code: "BCS", name: "Baja California Sur" },
    { code: "CAM", name: "Campeche" }, { code: "CHP", name: "Chiapas" }, { code: "CHH", name: "Chihuahua" },
    { code: "CMX", name: "Cidade do México" }, { code: "COA", name: "Coahuila" }, { code: "COL", name: "Colima" },
    { code: "DUR", name: "Durango" }, { code: "GUA", name: "Guanajuato" }, { code: "GRO", name: "Guerrero" },
    { code: "HID", name: "Hidalgo" }, { code: "JAL", name: "Jalisco" }, { code: "MEX", name: "Estado do México" },
    { code: "MIC", name: "Michoacán" }, { code: "MOR", name: "Morelos" }, { code: "NAY", name: "Nayarit" },
    { code: "NLE", name: "Nuevo León" }, { code: "OAX", name: "Oaxaca" }, { code: "PUE", name: "Puebla" },
    { code: "QUE", name: "Querétaro" }, { code: "ROO", name: "Quintana Roo" }, { code: "SLP", name: "San Luis Potosí" },
    { code: "SIN", name: "Sinaloa" }, { code: "SON", name: "Sonora" }, { code: "TAB", name: "Tabasco" },
    { code: "TAM", name: "Tamaulipas" }, { code: "TLA", name: "Tlaxcala" }, { code: "VER", name: "Veracruz" },
    { code: "YUC", name: "Yucatán" }, { code: "ZAC", name: "Zacatecas" },
  ],
  CA: [
    { code: "AB", name: "Alberta" }, { code: "BC", name: "Colúmbia Britânica" }, { code: "MB", name: "Manitoba" },
    { code: "NB", name: "Novo Brunswick" }, { code: "NL", name: "Terra Nova e Labrador" }, { code: "NS", name: "Nova Escócia" },
    { code: "NT", name: "Territórios do Noroeste" }, { code: "NU", name: "Nunavut" }, { code: "ON", name: "Ontário" },
    { code: "PE", name: "Ilha do Príncipe Eduardo" }, { code: "QC", name: "Quebec" }, { code: "SK", name: "Saskatchewan" },
    { code: "YT", name: "Yukon" },
  ],
  AU: [
    { code: "ACT", name: "Território da Capital Australiana" }, { code: "NSW", name: "Nova Gales do Sul" },
    { code: "NT", name: "Território do Norte" }, { code: "QLD", name: "Queensland" },
    { code: "SA", name: "Austrália do Sul" }, { code: "TAS", name: "Tasmânia" },
    { code: "VIC", name: "Vitória" }, { code: "WA", name: "Austrália Ocidental" },
  ],
  DE: [
    { code: "BB", name: "Brandemburgo" }, { code: "BE", name: "Berlim" }, { code: "BW", name: "Baden-Württemberg" },
    { code: "BY", name: "Baviera" }, { code: "HB", name: "Bremen" }, { code: "HE", name: "Hesse" },
    { code: "HH", name: "Hamburgo" }, { code: "MV", name: "Mecklemburgo-Pomerânia Ocidental" },
    { code: "NI", name: "Baixa Saxônia" }, { code: "NW", name: "Renânia do Norte-Vestfália" },
    { code: "RP", name: "Renânia-Palatinado" }, { code: "SH", name: "Schleswig-Holstein" },
    { code: "SL", name: "Sarre" }, { code: "SN", name: "Saxônia" }, { code: "ST", name: "Saxônia-Anhalt" },
    { code: "TH", name: "Turíngia" },
  ],
  ES: [
    { code: "AN", name: "Andaluzia" }, { code: "AR", name: "Aragão" }, { code: "AS", name: "Astúrias" },
    { code: "CB", name: "Cantábria" }, { code: "CE", name: "Ceuta" }, { code: "CL", name: "Castela e Leão" },
    { code: "CM", name: "Castela-La Mancha" }, { code: "CN", name: "Ilhas Canárias" }, { code: "CT", name: "Catalunha" },
    { code: "EX", name: "Extremadura" }, { code: "GA", name: "Galiza" }, { code: "IB", name: "Ilhas Baleares" },
    { code: "LO", name: "La Rioja" }, { code: "MA", name: "Madri" }, { code: "MC", name: "Múrcia" },
    { code: "ML", name: "Melilla" }, { code: "MU", name: "Múrcia" }, { code: "NA", name: "Navarra" },
    { code: "PV", name: "País Basco" }, { code: "RI", name: "La Rioja" }, { code: "VC", name: "Comunidade Valenciana" },
  ],
  FR: [
    { code: "ARA", name: "Auvérnia-Ródano-Alpes" }, { code: "BFC", name: "Borgonha-Franco-Condado" },
    { code: "BRE", name: "Bretanha" }, { code: "CVL", name: "Centro-Vale do Loire" },
    { code: "COR", name: "Córsega" }, { code: "GES", name: "Grande Leste" },
    { code: "HDF", name: "Altos da França" }, { code: "IDF", name: "Île-de-France" },
    { code: "NAQ", name: "Nova Aquitânia" }, { code: "NOR", name: "Normandia" },
    { code: "OCC", name: "Occitânia" }, { code: "PDL", name: "Países do Loire" },
    { code: "PAC", name: "Provença-Alpes-Costa Azul" },
  ],
  IT: [
    { code: "ABR", name: "Abruzzo" }, { code: "BAS", name: "Basilicata" }, { code: "CAL", name: "Calábria" },
    { code: "CAM", name: "Campânia" }, { code: "EMR", name: "Emília-Romanha" }, { code: "FVG", name: "Friul-Veneza Júlia" },
    { code: "LAZ", name: "Lácio" }, { code: "LIG", name: "Ligúria" }, { code: "LOM", name: "Lombardia" },
    { code: "MAR", name: "Marcas" }, { code: "MOL", name: "Molise" }, { code: "PIE", name: "Piemonte" },
    { code: "PUG", name: "Puglia" }, { code: "SAR", name: "Sardenha" }, { code: "SIC", name: "Sicília" },
    { code: "TOS", name: "Toscana" }, { code: "TAA", name: "Trentino-Alto Ádige" },
    { code: "UMB", name: "Úmbria" }, { code: "VDA", name: "Vale de Aosta" }, { code: "VEN", name: "Vêneto" },
  ],
  PT: [
    { code: "01", name: "Aveiro" }, { code: "02", name: "Beja" }, { code: "03", name: "Braga" },
    { code: "04", name: "Bragança" }, { code: "05", name: "Castelo Branco" }, { code: "06", name: "Coimbra" },
    { code: "07", name: "Évora" }, { code: "08", name: "Faro" }, { code: "09", name: "Guarda" },
    { code: "10", name: "Leiria" }, { code: "11", name: "Lisboa" }, { code: "12", name: "Portalegre" },
    { code: "13", name: "Porto" }, { code: "14", name: "Santarém" }, { code: "15", name: "Setúbal" },
    { code: "16", name: "Viana do Castelo" }, { code: "17", name: "Vila Real" }, { code: "18", name: "Viseu" },
    { code: "20", name: "Açores" }, { code: "30", name: "Madeira" },
  ],
  GB: [
    { code: "ENG", name: "Inglaterra" }, { code: "NIR", name: "Irlanda do Norte" },
    { code: "SCT", name: "Escócia" }, { code: "WLS", name: "País de Gales" },
  ],
};

// Helper: get states for a country
export function getStatesForCountry(countryCode: string): StateRegion[] {
  return STATES_BY_COUNTRY[countryCode] ?? [];
}

// Helper: get country by code
export function getCountryByCode(code: string): Country | undefined {
  return COUNTRIES.find((c) => c.code === code);
}

// Helper: get country name
export function getCountryName(code: string): string {
  return getCountryByCode(code)?.name ?? code;
}
