CREATE TABLE IF NOT EXISTS `meetings` (
  `id` int NOT NULL AUTO_INCREMENT,
  `createdById` int NOT NULL,
  `crsId` int NOT NULL,
  `taskId` int DEFAULT NULL,
  `title` varchar(256) NOT NULL,
  `description` text,
  `startDate` timestamp NOT NULL,
  `endDate` timestamp NOT NULL,
  `googleEventId` varchar(256) DEFAULT NULL,
  `googleMeetUrl` varchar(1024) DEFAULT NULL,
  `meetingCode` varchar(128) DEFAULT NULL,
  `participantIds` text,
  `participantEmails` text,
  `actualParticipants` text,
  `actualStartDate` timestamp NULL DEFAULT NULL,
  `actualEndDate` timestamp NULL DEFAULT NULL,
  `status` enum('scheduled','completed','canceled') NOT NULL DEFAULT 'scheduled',
  `lastSyncedAt` timestamp NULL DEFAULT NULL,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `meetings_createdById_idx` (`createdById`),
  KEY `meetings_crsId_idx` (`crsId`),
  KEY `meetings_taskId_idx` (`taskId`),
  KEY `meetings_startDate_idx` (`startDate`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;